"""empty message

Revision ID: caeecdcc3001
Revises: 8bd35429b07c
Create Date: 2024-10-13 01:10:43.021735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caeecdcc3001'
down_revision: Union[str, None] = '8bd35429b07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_email', 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('uq_user_email', 'users', type_='unique')
    # ### end Alembic commands ###
